#!/bin/sh
# cd to working dir
cd /tmp
if [ $# -ne 0 ]; then
    echo "usage: $0"
    exit 1
fi
rm -rf clixon
git clone https://github.com/clicon/clixon.git
if [ $? -ne 0 ]; then
   echo "Error in git clone"
   exit 1
fi
cd clixon
CFLAGS=-Werror ./configure
if [ $? -ne 0 ]; then
   echo "Error in configure"
   exit 1
fi
make
if [ $? -ne 0 ]; then
   echo "Error in make"
   exit 1
fi
sudo make install
if [ $? -ne 0 ]; then
   echo "Error in make install"
   exit 1
fi
sudo make install-include
if [ $? -ne 0 ]; then
   echo "Error in make install-include"
   exit 1
fi
cd example
make
if [ $? -ne 0 ]; then
    echo "Error in make"
    exit 1
fi
sudo make install
if [ $? -ne 0 ]; then
    echo "Error in make install"
    exit 1
fi
cd ../test
#./all.sh
(cd /home/olof/src/clixon/test; ./all.sh)
errcode=$?
if [ $errcode -ne 0 ]; then
   echo "test error"
   exit $errcode
fi
cd ../..
rm -rf clixon
