node {
     stage('Checkout') {
        git url: 'https://github.com/clicon/clixon.git'
        checkout scm
     }

     stage('Configure') {
        /* `make check` returns non-zero on test failures,
        * using `true` to allow the Pipeline to continue nonetheless
        */
        sh 'make clean || true'
        sh './configure || true'
     }

     stage('Make') {
        /* `make check` returns non-zero on test failures,
        * using `true` to allow the Pipeline to continue nonetheless
        */
        sh 'make || true'
     }

     stage('Testing') {

     }
}
