/*
 *
  ***** BEGIN LICENSE BLOCK *****
 
  Copyright (C) 2009-2017 Olof Hagsand and Benny Holmgren

  This file is part of CLIXON.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

  Alternatively, the contents of this file may be used under the terms of
  the GNU General Public License Version 3 or later (the "GPL"),
  in which case the provisions of the GPL are applicable instead
  of those above. If you wish to allow use of your version of this file only
  under the terms of the GPL, and not to allow others to
  use your version of this file under the terms of Apache License version 2, 
  indicate your decision by deleting the provisions above and replace them with
  the  notice and other provisions required by the GPL. If you do not delete
  the provisions above, a recipient may use your version of this file under
  the terms of any one of the Apache License version 2 or the GPL.

  ***** END LICENSE BLOCK *****

 *
 * Protocol to communicate between clients (eg clicon_cli, clicon_netconf) 
 * and server (clicon_backend)
 */

#ifdef HAVE_CONFIG_H
#include "clixon_config.h" /* generated by config & autoconf */
#endif

#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <assert.h>
#include <syslog.h>
#include <signal.h>
#include <ctype.h>
#include <sys/types.h>
#include <sys/time.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

/* cligen */
#include <cligen/cligen.h>

/* clicon */
#include "clixon_err.h"
#include "clixon_log.h"
#include "clixon_queue.h"
#include "clixon_chunk.h"
#include "clixon_sig.h"
#include "clixon_hash.h"
#include "clixon_handle.h"
#include "clixon_xml.h"
#include "clixon_proto.h"
#include "clixon_proto_encode.h"

struct clicon_msg *
clicon_msg_netconf_encode(char *format, ...)
{
    va_list            args;
    int                xmllen;
    int                len;
    struct clicon_msg *msg = NULL;
    int                hdrlen = sizeof(*msg);

    va_start(args, format);
    xmllen = vsnprintf(NULL, 0, format, args) + 1;
    va_end(args);

    len = hdrlen + xmllen;
    if ((msg = (struct clicon_msg *)malloc(len)) == NULL){
	clicon_err(OE_PROTO, errno, "malloc");
	return NULL;
    }
    memset(msg, 0, len);
    /* hdr */
    msg->op_type = htons(CLICON_MSG_NETCONF);
    msg->op_len = htons(len);

    /* body */
    va_start(args, format);
    vsnprintf(msg->op_body, xmllen, format, args);
    va_end(args);

    return msg;
}

struct clicon_msg *
clicon_msg_netconf_encode_xml(cxobj *xml)
{
    struct clicon_msg *msg = NULL;
    cbuf               *cb = NULL;

    if ((cb = cbuf_new()) == NULL){
	clicon_err(OE_XML, errno, "cbuf_new");
	goto done;
    }
    if (clicon_xml2cbuf(cb, xml, 0, 0) < 0)
	goto done;
    if ((msg = clicon_msg_netconf_encode("%s", cbuf_get(cb))) < 0)
	goto done;
  done:
    if (cb)
	cbuf_free(cb);
    return msg;
}

int
clicon_msg_netconf_decode(struct clicon_msg *msg, 
			  cxobj            **xml)
{
    int   retval = -1;
    char *xmlstr;

    /* body */
    xmlstr = msg->op_body;
    if (clicon_xml_parse_str(xmlstr, xml) < 0)
	goto done;
    retval = 0;
 done:
    return retval;
}

struct clicon_msg *
clicon_msg_change_encode(char       *db, 
			 uint32_t    op,	
			 char       *key, 
			 char       *str, 
			 uint32_t    str_len)
{
    struct clicon_msg *msg;
    uint16_t           len;
    int                hdrlen = sizeof(*msg);
    int                p;
    uint32_t           tmp;

    clicon_debug(2, "%s: op: %d str_len: %d db: %s key: '%s'", 
	    __FUNCTION__, 
	    op, str_len, db, key);
    p = 0;
    len = sizeof(*msg) + 2*sizeof(uint32_t) + strlen(db) + 1 + 
	strlen(key) + str_len;
    if (str_len)
	len++; /* if str not null add end of string */
    if ((msg = (struct clicon_msg *)malloc(len)) == NULL){
	clicon_err(OE_PROTO, errno, "malloc");
	return NULL;
    }
    memset(msg, 0, len);
    /* hdr */
    msg->op_type = htons(CLICON_MSG_CHANGE);
    msg->op_len = htons(len);

    /* body */
    tmp = htonl(op);
    memcpy(msg->op_body+p, &tmp, sizeof(uint32_t));
    p += sizeof(uint32_t);

    tmp = htonl(str_len);
    memcpy(msg->op_body+p, &tmp, sizeof(uint32_t));
    p += sizeof(uint32_t);
    strncpy(msg->op_body+p, db, len-p-hdrlen);
    p += strlen(db)+1;
    strncpy(msg->op_body+p, key, len-p-hdrlen);
    p += strlen(key)+1;
    if (str_len){
	memcpy(msg->op_body+p, str, str_len);
	p += str_len;
    }
    return msg;
}

int
clicon_msg_change_decode(struct clicon_msg *msg, 
			 char **db, 
			 uint32_t *op, 
			 char **key, 
			 char **str, 
			 uint32_t *str_len, 
			 const char *label)
{
    int p;
    uint32_t tmp;

    p = 0;
    /* body */
    memcpy(&tmp, msg->op_body+p, sizeof(uint32_t));
    *op = ntohl(tmp);
    p += sizeof(uint32_t);

    memcpy(&tmp, msg->op_body+p, sizeof(uint32_t));
    *str_len = ntohl(tmp);
    p += sizeof(uint32_t);

    if ((*db = chunk_sprintf(label, "%s", msg->op_body+p)) == NULL){
	clicon_err(OE_PROTO, errno, "%s: chunk_sprintf", 
		__FUNCTION__);
	return -1;
    }
    p += strlen(*db)+1;
    if ((*key = chunk_sprintf(label, "%s", msg->op_body+p)) == NULL){
	clicon_err(OE_PROTO, errno, "%s: chunk_sprintf", 
		__FUNCTION__);
	return -1;
    }
    p += strlen(*key)+1;

    if (*str_len){
	if ((*str = chunk(*str_len, label)) == NULL){
	    clicon_err(OE_PROTO, errno, "%s: chunk", 
		       __FUNCTION__);
	    return -1;
	}
	memcpy(*str, msg->op_body+p, *str_len);
	p += *str_len;
    }
    else
	*str = NULL;
    clicon_debug(2, "%s: op: %d str_len: %d db: %s key: '%s'", 
	    __FUNCTION__, 
	    *op, *str_len, *db, *key);
    return 0;
}



