FROM ubuntu:14.04
# 12.04
MAINTAINER Olof Hagsand <olof@hagsand.se>
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y libqdbm-dev
COPY libcligen.so.@CLIGEN_VERSION@ /usr/lib/
COPY libclicon.so.@CLICON_VERSION_MAJOR@ /usr/lib/
COPY libclicon_netconf.so.@CLIGEN_VERSION@ /usr/lib/
COPY clicon_netconf /usr/bin/
RUN ldconfig
CMD ["/usr/bin/clicon_netconf", "-f", "/data/clicon.conf"]







